User.create(name: "Peter", email: "peter@email.com", password: "password")
User.create(name: "Test", email: "test@email.com", password: "password")

Post.create(user_id: 1, title: Faker::Company.catch_phrase, body: Faker::Hipster.paragraph(sentence_count: 10), image: "http://lorempixel.com/640/480/")
Post.create(user_id: 1, title: Faker::Company.catch_phrase, body: Faker::Hipster.paragraph(sentence_count: 10), image: "http://lorempixel.com/640/480/")
Post.create(user_id: 1, title: Faker::Company.catch_phrase, body: Faker::Hipster.paragraph(sentence_count: 10), image: "http://lorempixel.com/640/480/")
Post.create(user_id: 1, title: Faker::Company.catch_phrase, body: Faker::Hipster.paragraph(sentence_count: 10), image: "http://lorempixel.com/640/480/")
Post.create(user_id: 1, title: Faker::Company.catch_phrase, body: Faker::Hipster.paragraph(sentence_count: 10), image: "http://lorempixel.com/640/480/")
Post.create(user_id: 1, title: Faker::Company.catch_phrase, body: Faker::Hipster.paragraph(sentence_count: 10), image: "http://lorempixel.com/640/480/")
Post.create(user_id: 2, title: Faker::Company.catch_phrase, body: Faker::Hipster.paragraph(sentence_count: 10), image: "http://lorempixel.com/640/480/")
Post.create(user_id: 2, title: Faker::Company.catch_phrase, body: Faker::Hipster.paragraph(sentence_count: 10), image: "http://lorempixel.com/640/480/")
Post.create(user_id: 2, title: Faker::Company.catch_phrase, body: Faker::Hipster.paragraph(sentence_count: 10), image: "http://lorempixel.com/640/480/")
